layout: siderbar
style: light
# Site settings
title: Yingfan Blog
email: yingfanduan901@gmail.com
description: "本科应用统计在读，数据分析"
url: "https://yingfan-duan.github.io"

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name
# SNS settings
RSS: false
# social_media: 
  # facebook: Ivy Duan
  # instagram: ivyyyduan
  # WeChat: BULIN-D
  # linkedin: Yingfan Duan
  # Email: yingfanduan901@gmail.com


topics:
  - name: CSS
    web_url: https://github.com/topics/css
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Web design

  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
